Initial wayland config

diff --git a/.local/bin/sel-area b/.local/bin/sel-area
--- a/.local/bin/sel-area
+++ b/.local/bin/sel-area
@@ -1,8 +1,10 @@
 #!/bin/sh
-# Utility script to get the geometry of a selected region.
+# Get the geometry of a selected region.
+
+. ~/.cache/rswal/colors.sh
 
 ALPHA=0.5
-COLOR="$(xrdb -get color12)"
+COLOR="$(get_color 12)"
 
 hex_to_rgb() {
     color="$(echo "${1#?}" | tr '[:lower:]' '[:upper:]')"
@@ -18,10 +20,68 @@ hex_to_rgb() {
     done
 }
 
+get_focused_screen_resolution() {
+    case "$XDG_SESSION_TYPE" in
+        x11)
+            xrandr --current | grep -o 'current [0-9]* x [0-9]*' | tr -d 'curent ' 'x' ' ' | tr 'x' ' '
+            return
+            ;;
+        wayland)
+            case "$XDG_CURRENT_DESKTOP" in
+                Hyprland)
+                    hyprctl -j monitors | jq -r '.[] | select(.focused) | "\(.width) \(.height)"'
+                    ;;
+                *)
+                    echo "error: unsupported wayland compositor"
+                    return 1
+                    ;;
+            esac
+            ;;
+        *)
+            echo "error: unsupported session type"
+            return 1
+            ;;
+    esac
+}
+
 if [ "$1" = "full" ]; then
-    resolution="$(xrandr --current | grep -o 'current [0-9]* x [0-9]*' | tr -d 'curent ')"
-    echo "$resolution+0+0"
+    resolution="$(get_focused_screen_resolution)" || exit 1
+    echo "0 0 $resolution"
     exit
 fi
 
-exec slop --highlight --color="$(hex_to_rgb "$COLOR"),$ALPHA"
+regions=""
+case "$XDG_SESSION_TYPE" in
+    x11)
+        selection_color="$(hex_to_rgb "$COLOR"),$ALPHA"
+        set -- slop --format="%x %y %w %h" --highlight --color="$selection_color"
+        ;;
+    wayland)
+        selection_color="$COLOR$(echo "scale=0;obase=16; (255 * $ALPHA)/1" | bc)"
+        set -- slurp -f "%x %y %w %h
+" -b "#00000000" \
+            -B "#00000000" \
+            -c "${COLOR}ff" \
+            -s "$selection_color" \
+            -w 1 \
+            -o
+
+        case "$XDG_CURRENT_DESKTOP" in
+            Hyprland)
+                workspaces="$(hyprctl monitors -j | jq -r 'map(.activeWorkspace.id)')"
+                regions="$(
+                    hyprctl clients -j |
+                        jq -r --argjson workspaces "$workspaces" 'map(select([.workspace.id] | inside($workspaces)))' |
+                        jq -r '.[] | "\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"'
+                )"
+                ;;
+            *) regions="" ;;
+        esac
+        ;;
+    *)
+        echo "error: unsupported session type"
+        exit 1
+        ;;
+esac
+
+echo "$regions" | exec "$@"
diff --git a/.local/bin/snip b/.local/bin/snip
--- a/.local/bin/snip
+++ b/.local/bin/snip
@@ -1,22 +1,40 @@
 #!/bin/sh
-# This script provides a hassle-free way of taking screenshots.
-
-set -e
+# Take screenshots for a region or the entire screen.
 
 SCREENSHOT_DIR="$(xdg-user-dir PICTURES)/screenshots"
 SCREENSHOT_FORMAT='+%Y-%m-%d_%H-%M-%S'
 
 snip_to() {
-    if [ "$1" = "clip" ]; then
-        message="The screenshot has been successfully saved to your clipboard."
-        output="-"
-    else
-        # shellcheck disable=2088
-        output="$SCREENSHOT_DIR/$(date "$SCREENSHOT_FORMAT").png"
-        message="The screenshot has been successfully saved as $(echo "$output" | sed "s|$HOME|~|")."
-    fi
+    mode="$1"
+    x="$2"
+    y="$3"
+    width="$4"
+    height="$5"
 
-    shotgun -g "$2" "$output" | xclip -sel c -target image/png
+    case "$mode" in
+        clip)
+            message="The screenshot has been successfully saved to your clipboard."
+            output="-"
+            ;;
+        file)
+            output="$SCREENSHOT_DIR/$(date "$SCREENSHOT_FORMAT").png"
+            message="The screenshot has been successfully saved as $(echo "$output" | sed "s|$HOME|~|")."
+            ;;
+    esac
+
+    case "$XDG_SESSION_TYPE" in
+        x11)
+            shotgun -g "${width}x$height+$x+$y" "$output" | xclip -sel c -target image/png
+            ;;
+        wayland)
+            grim -g "$x,$y ${width}x$height" -c "$output" | wl-copy --type image/png
+            ;;
+        *)
+            echo "error: unsupported session type"
+            return 1
+            ;;
+    esac || return 1
+
     notify-send \
         --icon=accessories-screenshot-symbolic \
         --expire-time=3000 \
@@ -35,7 +53,7 @@ case "$1" in
 🖱 Selection (Copy)
 💻 Entire Screen (Copy)"
 
-        choice="$(echo "$choices" | dmenu -i -p "Screenshot:")" || exit
+        choice="$(echo "$choices" | menu -i -p "Screenshot:")" || exit
         case "$choice" in
             *Selection*) region="sel" ;;
             *) region="full" ;;
@@ -48,5 +66,7 @@ case "$1" in
         ;;
 esac
 
-sel="$(sel-area "$region")"
-snip_to "$mode" "$sel"
+selection="$(sel-area "$region")" || exit
+
+# shellcheck disable=SC2086
+snip_to "$mode" $selection || exit 1
